version: '3'

volumes:
  server-data:

services:
  server:
    restart: always
    container_name: ${COMPOSE_PROJECT_NAME}_server
    #image: hermsi/mordhau-server:latest
    # If you want to build from fresh source every "docker-compose up" ...
    # ... remove the "image:"-key and uncomment the following two lines:
    build:
      context: ../.
    volumes:
      - server-data:/app
    environment:
      - SESSION_NAME=${SESSION_NAME}
      - SERVER_PASSWORD=${SERVER_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - MAX_PLAYERS=${MAX_PLAYERS}
    ports:
      # Port for connections from game client
      - "7777:7777/udp"
      # Steam's server-list port
      - "27015:27015/udp"
    networks:
      - default
